const bcrypt = require('bcryptjs');
const db = require('../models');
const { Usuario, Salon, Servicio, Consulta } = db;

async function seedDatabase() {
    try {
        console.log('🌱 Iniciando carga de datos de ejemplo...');

        // Limpiar base de datos (opcional - comentar si no quieres borrar datos existentes)
        await Consulta.destroy({ where: {}, force: true });
        await Salon.destroy({ where: {}, force: true });
        await Servicio.destroy({ where: {}, force: true });
        await Usuario.destroy({ where: {}, force: true });

        // Crear usuarios de ejemplo
        const hashedPassword = await bcrypt.hash('password123', 10);

        const usuarios = await Usuario.bulkCreate([
            {
                email: 'proveedor1@tusalon.com',
                password: hashedPassword,
                nombre: 'María',
                apellido: 'González',
                telefono: '+54 11 1234-5678',
                tipoUsuario: 'proveedor',
                verificado: true,
                activo: true,
            },
            {
                email: 'proveedor2@tusalon.com',
                password: hashedPassword,
                nombre: 'Carlos',
                apellido: 'Rodríguez',
                telefono: '+54 11 8765-4321',
                tipoUsuario: 'proveedor',
                verificado: true,
                activo: true,
            },
            {
                email: 'cliente1@tusalon.com',
                password: hashedPassword,
                nombre: 'Ana',
                apellido: 'Martínez',
                telefono: '+54 11 5555-1111',
                tipoUsuario: 'cliente',
                verificado: true,
                activo: true,
            },
            {
                email: 'admin@tusalon.com',
                password: hashedPassword,
                nombre: 'Admin',
                apellido: 'Sistema',
                telefono: '+54 11 9999-0000',
                tipoUsuario: 'admin',
                verificado: true,
                activo: true,
            },
        ]);

        console.log('✅ Usuarios creados:', usuarios.length);

        // Crear salones de ejemplo (Buenos Aires)
        const salones = await Salon.bulkCreate([
            {
                usuarioId: usuarios[0].id,
                nombre: 'Salón Elegancia',
                descripcion: 'Salón de eventos premium con vista panorámica de la ciudad. Ideal para bodas y eventos corporativos. Amplios ventanales con luz natural, pista de baile profesional y zona de cocktail.',
                direccion: 'Av. Libertador 2250',
                ciudad: 'Buenos Aires',
                provincia: 'Buenos Aires',
                codigoPostal: 'C1425AAJ',
                pais: 'Argentina',
                latitud: -34.5831,
                longitud: -58.3916,
                capacidad: 200,
                precioBase: 150000.00,
                imagenes: ['https://images.unsplash.com/photo-1519167758481-83f29da8c1f8?w=800', 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=800'],
                serviciosIncluidos: ['Catering', 'Música', 'Decoración básica', 'Estacionamiento'],
                activo: true,
            },
            {
                usuarioId: usuarios[0].id,
                nombre: 'Jardín de Eventos Los Jazmines',
                descripcion: 'Hermoso jardín al aire libre de 1000m² perfecto para ceremonias y recepciones. Incluye sector cubierto climatizado. Árboles centenarios y fuente de agua.',
                direccion: 'Calle Falsa 123',
                ciudad: 'Buenos Aires',
                provincia: 'Buenos Aires',
                codigoPostal: 'C1000',
                pais: 'Argentina',
                latitud: -34.6037,
                longitud: -58.3816,
                capacidad: 150,
                precioBase: 120000.00,
                imagenes: ['https://images.unsplash.com/photo-1478146896981-b80fe463b330?w=800', 'https://images.unsplash.com/photo-1532712938310-34cb3982ef74?w=800'],
                serviciosIncluidos: ['Jardín', 'Estacionamiento', 'Sanitarios', 'Sector cubierto'],
                activo: true,
            },
            {
                usuarioId: usuarios[1].id,
                nombre: 'Grand Palace',
                descripcion: 'Salón de lujo con instalaciones de primera categoría. Techos de 8 metros, candelabros de cristal, pisos de mármol italiano. El lugar perfecto para eventos inolvidables.',
                direccion: 'Av. Corrientes 5000',
                ciudad: 'Buenos Aires',
                provincia: 'Buenos Aires',
                codigoPostal: 'C1414',
                pais: 'Argentina',
                latitud: -34.6131,
                longitud: -58.4278,
                capacidad: 300,
                precioBase: 250000.00,
                imagenes: ['https://images.unsplash.com/photo-1529636798458-92182e662485?w=800', 'https://images.unsplash.com/photo-1478146896981-b80fe463b330?w=800', 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800'],
                serviciosIncluidos: ['Catering premium', 'Valet parking', 'Decoración', 'Iluminación profesional', 'Sonido', 'Proyector'],
                activo: true,
            },
            {
                usuarioId: usuarios[0].id,
                nombre: 'La Terraza de Palermo',
                descripcion: 'Moderna terraza con vista a los bosques de Palermo. Ideal para eventos al atardecer. Decoración minimalista y elegante. Toldo retráctil para cualquier clima.',
                direccion: 'Av. del Libertador 3800',
                ciudad: 'Buenos Aires',
                provincia: 'Buenos Aires',
                codigoPostal: 'C1426',
                pais: 'Argentina',
                latitud: -34.5641,
                longitud: -58.4173,
                capacidad: 120,
                precioBase: 95000.00,
                imagenes: ['https://images.unsplash.com/photo-1519167758481-83f29da8c1f8?w=800', 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=800'],
                serviciosIncluidos: ['Vista panorámica', 'Toldo', 'Bar', 'Cocina equipada'],
                activo: true,
            },
            {
                usuarioId: usuarios[1].id,
                nombre: 'Salón Victoria',
                descripcion: 'Salón clásico con más de 50 años de trayectoria. Arquitectura europea, jardín privado con pérgola. Capacidad para ceremonias religiosas. Totalmente renovado en 2023.',
                direccion: 'Av. Santa Fe 4500',
                ciudad: 'Buenos Aires',
                provincia: 'Buenos Aires',
                codigoPostal: 'C1425',
                pais: 'Argentina',
                latitud: -34.5889,
                longitud: -58.4156,
                capacidad: 180,
                precioBase: 135000.00,
                imagenes: ['https://images.unsplash.com/photo-1478146896981-b80fe463b330?w=800', 'https://images.unsplash.com/photo-1532712938310-34cb3982ef74?w=800'],
                serviciosIncluidos: ['Jardín privado', 'Pérgola', 'Salón principal', 'Sala de estar'],
                activo: true,
            },
            {
                usuarioId: usuarios[0].id,
                nombre: 'Espacio Urbano Loft',
                descripcion: 'Loft industrial de 400m² con techos de 6 metros. Excelente para eventos corporativos, lanzamientos de productos o bodas modernas. Ladrillo a la vista y grandes ventanales.',
                direccion: 'Miranda 2850',
                ciudad: 'Buenos Aires',
                provincia: 'Buenos Aires',
                codigoPostal: 'C1425',
                pais: 'Argentina',
                latitud: -34.5724,
                longitud: -58.4297,
                capacidad: 100,
                precioBase: 80000.00,
                imagenes: ['https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800', 'https://images.unsplash.com/photo-1519167758481-83f29da8c1f8?w=800'],
                serviciosIncluidos: ['Wifi', 'Proyector', 'Sonido', 'Iluminación LED'],
                activo: true,
            },
            {
                usuarioId: usuarios[1].id,
                nombre: 'Quinta La Rosaleda',
                descripcion: 'Quinta de 3000m² con casona colonial restaurada. Parque con rosales, lago artificial y gazebo. Perfecta para bodas campestres. A 30 min del centro.',
                direccion: 'Camino Provincial 123',
                ciudad: 'Pilar',
                provincia: 'Buenos Aires',
                codigoPostal: 'B1629',
                pais: 'Argentina',
                latitud: -34.4587,
                longitud: -58.9144,
                capacidad: 250,
                precioBase: 180000.00,
                imagenes: ['https://images.unsplash.com/photo-1478146896981-b80fe463b330?w=800', 'https://images.unsplash.com/photo-1532712938310-34cb3982ef74?w=800', 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=800'],
                serviciosIncluidos: ['Parque 3000m²', 'Lago', 'Gazebo', 'Casona colonial', 'Estacionamiento 50 autos'],
                activo: true,
            },
            {
                usuarioId: usuarios[0].id,
                nombre: 'Salón Las Magnolias',
                descripcion: 'Salón familiar con excelente relación precio-calidad. Cocina propia, equipo de sonido incluido. Ambiente cálido y acogedor. Ideal para eventos de hasta 100 personas.',
                direccion: 'Av. Rivadavia 8900',
                ciudad: 'Buenos Aires',
                provincia: 'Buenos Aires',
                codigoPostal: 'C1406',
                pais: 'Argentina',
                latitud: -34.6377,
                longitud: -58.5007,
                capacidad: 100,
                precioBase: 70000.00,
                imagenes: ['https://images.unsplash.com/photo-1519167758481-83f29da8c1f8?w=800'],
                serviciosIncluidos: ['Cocina equipada', 'Sonido', 'Mesas y sillas', 'Vajilla'],
                activo: true,
            },
            {
                usuarioId: usuarios[1].id,
                nombre: 'Casa Eventos Puerto Madero',
                descripcion: 'Moderno espacio en pleno Puerto Madero con vista al río. Diseño contemporáneo, tecnología de punta. Terraza exclusiva en el último piso. Catering a cargo de chef reconocido.',
                direccion: 'Av. Alicia Moreau de Justo 1920',
                ciudad: 'Buenos Aires',
                provincia: 'Buenos Aires',
                codigoPostal: 'C1107',
                pais: 'Argentina',
                latitud: -34.6118,
                longitud: -58.3621,
                capacidad: 160,
                precioBase: 280000.00,
                imagenes: ['https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800', 'https://images.unsplash.com/photo-1519167758481-83f29da8c1f8?w=800', 'https://images.unsplash.com/photo-1478146896981-b80fe463b330?w=800'],
                serviciosIncluidos: ['Vista al río', 'Terraza rooftop', 'Catering chef', 'Valet parking', 'Wifi', 'Climatización'],
                activo: true,
            },
            {
                usuarioId: usuarios[0].id,
                nombre: 'El Quincho de Don Carlos',
                descripcion: 'Quincho estilo campo argentino con parrilla profesional. Galería cubierta de 200m², patio con quincho al aire libre. Perfecto para asados y eventos informales. Ambiente rústico y auténtico.',
                direccion: 'Ruta 8 Km 45',
                ciudad: 'Pilar',
                provincia: 'Buenos Aires',
                codigoPostal: 'B1629',
                pais: 'Argentina',
                latitud: -34.4724,
                longitud: -58.8897,
                capacidad: 80,
                precioBase: 60000.00,
                imagenes: ['https://images.unsplash.com/photo-1478146896981-b80fe463b330?w=800', 'https://images.unsplash.com/photo-1532712938310-34cb3982ef74?w=800'],
                serviciosIncluidos: ['Parrilla profesional', 'Quincho', 'Galería cubierta', 'Juegos de mesa'],
                activo: true,
            },
        ]);

        console.log('✅ Salones creados:', salones.length);

        // Crear servicios de ejemplo
        const servicios = await Servicio.bulkCreate([
            // SERVICIOS DE FOTOGRAFÍA
            {
                usuarioId: usuarios[1].id,
                tipo: 'fotografia',
                nombre: 'Foto Arte Eventos',
                descripcion: 'Fotografía profesional para bodas y eventos sociales con 15 años de experiencia. Equipo de 2 fotógrafos, cobertura completa del evento, entrega de 500+ fotos editadas en alta resolución. Álbum digital incluido. Estilo documental y artístico.',
                ciudad: 'Buenos Aires',
                provincia: 'Buenos Aires',
                pais: 'Argentina',
                latitud: -34.5975,
                longitud: -58.3832,
                precioDesde: 80000.00,
                imagenes: ['https://images.unsplash.com/photo-1606216794074-735e91aa2c92?w=800', 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=800'],
                contactoEmail: 'info@fotoarte.com',
                contactoTelefono: '+54 11 2222-3333',
                sitioWeb: 'https://fotoarte.com',
                activo: true,
            },
            {
                usuarioId: usuarios[0].id,
                tipo: 'fotografia',
                nombre: 'Momentos Perfectos Fotografía',
                descripcion: 'Especializados en fotografía de bodas con estilo romántico y natural. Incluye sesión pre-boda en exteriores, cobertura de ceremonia y fiesta (hasta 8 horas), álbum premium de 40 páginas y galería online privada. Retoque profesional de todas las imágenes.',
                ciudad: 'Buenos Aires',
                provincia: 'Buenos Aires',
                pais: 'Argentina',
                latitud: -34.6037,
                longitud: -58.3816,
                precioDesde: 95000.00,
                imagenes: ['https://images.unsplash.com/photo-1519741497674-611481863552?w=800', 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=800'],
                contactoEmail: 'contacto@momentosperfectos.com.ar',
                contactoTelefono: '+54 11 3344-5566',
                sitioWeb: 'https://momentosperfectos.com.ar',
                activo: true,
            },
            {
                usuarioId: usuarios[1].id,
                tipo: 'fotografia',
                nombre: 'Lente Creativo Studio',
                descripcion: 'Fotografía artística y creativa para eventos exclusivos. Utilizamos técnicas de iluminación profesional y edición cinematográfica. Paquete incluye: 2 fotógrafos, drone para tomas aéreas, video highlight de 3 minutos y entrega en USB personalizado. Estilo editorial.',
                ciudad: 'Buenos Aires',
                provincia: 'Buenos Aires',
                pais: 'Argentina',
                latitud: -34.5831,
                longitud: -58.3916,
                precioDesde: 120000.00,
                imagenes: ['https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=800', 'https://images.unsplash.com/photo-1460978812857-470ed1c77af0?w=800'],
                contactoEmail: 'info@lentecreativo.com',
                contactoTelefono: '+54 11 5577-8899',
                sitioWeb: 'https://lentecreativo.com',
                activo: true,
            },
            {
                usuarioId: usuarios[0].id,
                tipo: 'fotografia',
                nombre: 'Claudio Méndez Fotografía',
                descripcion: 'Fotógrafo profesional con 20 años de trayectoria. Ganador de premios internacionales en fotografía de bodas. Estilo fotoperíodistico, capturo emociones reales sin poses forzadas. Incluye álbum artesanal, pen drive con todas las fotos editadas y cuadro canvas 70x50cm de regalo.',
                ciudad: 'Buenos Aires',
                provincia: 'Buenos Aires',
                pais: 'Argentina',
                latitud: -34.5889,
                longitud: -58.4156,
                precioDesde: 110000.00,
                imagenes: ['https://images.unsplash.com/photo-1519741497674-611481863552?w=800', 'https://images.unsplash.com/photo-1606216794074-735e91aa2c92?w=800'],
                contactoEmail: 'claudio@mendesfoto.com',
                contactoTelefono: '+54 11 6677-8899',
                sitioWeb: 'https://claudiomendezfoto.com',
                activo: true,
            },
            {
                usuarioId: usuarios[1].id,
                tipo: 'fotografia',
                nombre: 'Flash & Focus Producciones',
                descripcion: 'Equipo de 3 fotógrafos especializados en eventos corporativos y sociales. Cobertura integral con múltiples ángulos. Entrega express en 48hs. Incluye: galería online, código QR para compartir con invitados, impresiones ilimitadas y video resumen. Descuentos para eventos empresariales recurrentes.',
                ciudad: 'Buenos Aires',
                provincia: 'Buenos Aires',
                pais: 'Argentina',
                latitud: -34.6118,
                longitud: -58.3621,
                precioDesde: 75000.00,
                imagenes: ['https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=800', 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=800'],
                contactoEmail: 'ventas@flashfocus.com.ar',
                contactoTelefono: '+54 11 4455-6677',
                sitioWeb: 'https://flashfocus.com.ar',
                activo: true,
            },

            // OTROS SERVICIOS
            {
                usuarioId: usuarios[1].id,
                tipo: 'dj',
                nombre: 'DJ Sound Pro',
                descripcion: 'DJ profesional con equipamiento de última generación Pioneer. Música para todos los gustos y edades. Más de 300 eventos realizados. Incluye: luces LED, pantalla de humo, micrófono inalámbrico y playlist personalizada según tus preferencias.',
                ciudad: 'Buenos Aires',
                provincia: 'Buenos Aires',
                pais: 'Argentina',
                latitud: -34.6158,
                longitud: -58.4333,
                precioDesde: 50000.00,
                imagenes: ['https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800'],
                contactoEmail: 'dj@soundpro.com',
                contactoTelefono: '+54 11 4444-5555',
                sitioWeb: 'https://soundpro.com',
                activo: true,
            },
            {
                usuarioId: usuarios[0].id,
                tipo: 'wedding_planner',
                nombre: 'Eventos Perfectos',
                descripcion: 'Organización integral de bodas y eventos sociales. Hacemos realidad tu sueño. Asesoramiento completo desde la elección del salón hasta el último detalle. Coordinación el día del evento, gestión de proveedores, cronograma personalizado y asistente de ceremonias.',
                ciudad: 'Buenos Aires',
                provincia: 'Buenos Aires',
                pais: 'Argentina',
                latitud: -34.5889,
                longitud: -58.3956,
                precioDesde: 120000.00,
                imagenes: ['https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800', 'https://images.unsplash.com/photo-1478146896981-b80fe463b330?w=800'],
                contactoEmail: 'info@eventosperfectos.com',
                contactoTelefono: '+54 11 6666-7777',
                sitioWeb: 'https://eventosperfectos.com',
                activo: true,
            },
            {
                usuarioId: usuarios[1].id,
                tipo: 'catering',
                nombre: 'Catering Deluxe',
                descripcion: 'Servicio de catering gourmet para eventos exclusivos. Menú degustación previo incluido. Chef con experiencia internacional. Opciones: menú tradicional, fusion, vegano/vegetariano. Precio por persona incluye: entrada, plato principal, postre, pan, bebidas y servicio de mozos.',
                ciudad: 'Buenos Aires',
                provincia: 'Buenos Aires',
                pais: 'Argentina',
                latitud: -34.6092,
                longitud: -58.3842,
                precioDesde: 5000.00,
                imagenes: ['https://images.unsplash.com/photo-1555244162-803834f70033?w=800'],
                contactoEmail: 'info@cateringdeluxe.com',
                contactoTelefono: '+54 11 8888-9999',
                sitioWeb: 'https://cateringdeluxe.com',
                activo: true,
            },
            {
                usuarioId: usuarios[0].id,
                tipo: 'video',
                nombre: 'Cinemática Producciones',
                descripcion: 'Video cinematográfico para bodas y eventos. Equipamiento 4K, drones, estabilizadores. Editado con música original, efectos especiales y corrección de color profesional. Entrega: video completo (1-2hs), video resumen (10min) y teaser para redes (1min). Incluye Blu-ray y descarga digital.',
                ciudad: 'Buenos Aires',
                provincia: 'Buenos Aires',
                pais: 'Argentina',
                latitud: -34.5724,
                longitud: -58.4297,
                precioDesde: 90000.00,
                imagenes: ['https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=800'],
                contactoEmail: 'info@cinematica.com.ar',
                contactoTelefono: '+54 11 7788-9900',
                sitioWeb: 'https://cinematica.com.ar',
                activo: true,
            },
            {
                usuarioId: usuarios[1].id,
                tipo: 'decoracion',
                nombre: 'Ambientes Únicos Decoración',
                descripcion: 'Decoración y ambientación personalizada para eventos. Trabajamos con telas, flores naturales, iluminación especial y mobiliario. Diseño a medida según temática elegida (clásico, rústico, vintage, moderno). Incluye montaje, desmontaje y coordinación con el salón.',
                ciudad: 'Buenos Aires',
                provincia: 'Buenos Aires',
                pais: 'Argentina',
                latitud: -34.6377,
                longitud: -58.5007,
                precioDesde: 65000.00,
                imagenes: ['https://images.unsplash.com/photo-1478146896981-b80fe463b330?w=800', 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800'],
                contactoEmail: 'contacto@ambientesunicoes.com',
                contactoTelefono: '+54 11 3322-4455',
                sitioWeb: 'https://ambientesunicosdeco.com',
                activo: true,
            },
            {
                usuarioId: usuarios[0].id,
                tipo: 'dj',
                nombre: 'DJs Platinum Team',
                descripcion: 'Grupo de DJs especializados en fiestas y eventos. Amplio repertorio musical: actualidad, clásicos, latinos, electrónica. Equipamiento de sonido e iluminación profesional. Show en vivo, animación y efectos especiales. Consultar disponibilidad para eventos temáticos.',
                ciudad: 'Buenos Aires',
                provincia: 'Buenos Aires',
                pais: 'Argentina',
                latitud: -34.5641,
                longitud: -58.4173,
                precioDesde: 60000.00,
                imagenes: ['https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800'],
                contactoEmail: 'team@djsplatinum.com',
                contactoTelefono: '+54 11 9988-7766',
                sitioWeb: 'https://djsplatinum.com',
                activo: true,
            },
        ]);

        console.log('✅ Servicios creados:', servicios.length);

        // Crear consultas de ejemplo
        const consultas = await Consulta.bulkCreate([
            {
                clienteId: usuarios[2].id,
                proveedorId: usuarios[0].id,
                tipoConsulta: 'salon',
                salonId: salones[0].id,
                fechaEvento: '2024-06-15',
                numeroInvitados: 180,
                mensaje: 'Hola, me interesa el salón para mi boda en junio. ¿Está disponible? ¿Qué incluye el precio base?',
                estado: 'pendiente',
            },
            {
                clienteId: usuarios[2].id,
                proveedorId: usuarios[1].id,
                tipoConsulta: 'servicio',
                servicioId: servicios[0].id,
                fechaEvento: '2024-06-15',
                numeroInvitados: 180,
                mensaje: 'Necesito cotización para fotografía de boda. ¿Cuántas horas incluye el paquete?',
                estado: 'contactado',
                respuestaProveedor: 'Hola! El paquete incluye 8 horas de cobertura. Te envío más detalles por email.',
                fechaRespuesta: new Date(),
            },
        ]);

        console.log('✅ Consultas creadas:', consultas.length);

        console.log('\n🎉 ¡Datos de ejemplo cargados exitosamente!');
        console.log('\n📋 Resumen:');
        console.log(`   - ${usuarios.length} usuarios`);
        console.log(`   - ${salones.length} salones`);
        console.log(`   - ${servicios.length} servicios`);
        console.log(`   - ${consultas.length} consultas`);
        console.log('\n🔑 Credenciales de prueba:');
        console.log('   Email: proveedor1@tusalon.com | Password: password123');
        console.log('   Email: cliente1@tusalon.com | Password: password123');
        console.log('   Email: admin@tusalon.com | Password: password123');

        process.exit(0);
    } catch (error) {
        console.error('❌ Error al cargar datos:', error);
        process.exit(1);
    }
}

// Ejecutar el seeder
seedDatabase();
